name: CoinToss
main: net.primomc.CoinToss.CoinToss
version: 1.1.1
author: kukelekuuk00
depend: [Vault]

commands:
  cointoss:
    description: The Coin Toss command
    aliases: [toss, ctoss]
    permission: cointoss.use
