name: CoinToss
main: net.primomc.CoinToss.CoinToss
version: 1.1.2
author: kukelekuuk00
depend: [Vault]
api-version: '1.13'

commands:
  cointoss:
    description: The Coin Toss command
    aliases: [toss, ctoss]
    permission: cointoss.use
